replicaCount: 2

replicaSetName: rs0

image:
  repository: mongo
  tag: "7.0"
  pullPolicy: Always

persistence:
  storageClass: gp3
  size: 10Gi

resources:
  requests:
    cpu: 250m
    memory: 512Mi

  limits:
    cpu: 500m
    memory: 1Gi

externalSecret:
  awsSecretName: roboshop/dev/mongodb